version: '3.4'

services:
  watch-gulp:
    build:
      context: .
      target: gulp
    command: bash -c "npx gulp assemble --environment=development --sass-lint=${LINT_SASS} && npx gulp watch --environment=development --sass-lint=${LINT_SASS}"
    volumes:
      - ./libero-config:/app/libero-config
      - ./source:/app/source
  watch-build:
    build:
      context: .
      target: build
    command: core/watch
    volumes:
      - public:/app/public
      - ./source:/app/source:ro
    depends_on:
      - watch-gulp
  ui:
    build:
      context: .
      target: gulp
    command: npx gulp server
    ports:
      - 8889:80
      - 3000:3000
    volumes:
      - public:/app/public:ro
    depends_on:
      - watch-build

volumes:
  public:
